services:
  mysql:
    image: mysql:8.0.40
    container_name: mysql
    ports:
      - "3366:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "db_node_demo"
      MYSQL_USER: "new_user"
      MYSQL_PASSWORD: "root"
    volumes:
      - 'mysql:/var/lib/mysql'

  nodejs_app:
    build: .
    depends_on:
      - mysql
    container_name: node_app
    ports:
      - "5000:5000"
    environment:
      DB_CONNECTION : "mysql"
      DB_HOST : mysql
      DB_PORT : "3306"
      DB_DATABASE : "db_node_demo"
      DB_USERNAME : "root"
      DB_PASSWORD : "root"
      APP_PORT : 5000

  phpmyadmin:
    image: phpmyadmin:5.2
    depends_on:
      - mysql
      - nodejs_app
    container_name: phpmyadmin
    ports:
      - "5001:80"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      PMA_HOST: mysql

volumes:
  mysql:
